Starting Nmap 7.93 ( https://nmap.org ) at 2022-12-02 07:40 PST
Nmap scan report for alice.hachyderm.io (63.228.108.114)
Host is up (0.0019s latency).
Not shown: 997 filtered tcp ports (no-response)
PORT    STATE SERVICE
22/tcp  open  ssh
80/tcp  open  http
| http-headers: 
|   Server: nginx/1.22.1
|   Date: Fri, 02 Dec 2022 15:41:02 GMT
|   Content-Type: text/html
|   Content-Length: 153
|   Connection: close
|   
|_  (Request type: GET)
443/tcp open  https
| http-headers: 
|   Server: nginx/1.22.1
|   Date: Fri, 02 Dec 2022 15:41:02 GMT
|   Content-Type: application/octet-stream
|   Content-Length: 0
|   Connection: close
|   
|_  (Request type: HEAD)

Nmap done: 1 IP address (1 host up) scanned in 5.07 seconds
