#!/bin/bash
# =========================================================================== #
#            MIT License Copyright (c) 2022 Kris Nóva <kris@nivenly.com>      #
#                                                                             #
#                 +-----------------------------------------+                 #
#                 |   ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗   |                 #
#                 |   ████╗  ██║██╔═████╗██║   ██║██╔══██╗  |                 #
#                 |   ██╔██╗ ██║██║██╔██║██║   ██║███████║  |                 #
#                 |   ██║╚██╗██║████╔╝██║╚██╗ ██╔╝██╔══██║  |                 #
#                 |   ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║  |                 #
#                 |   ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝  |                 #
#                 +-----------------------------------------+                 #
#                                                                             #
#                        This machine kills fascists.                         #
#                                                                             #
# =========================================================================== #
#
if [ -z "$1" ]; then
    echo "Usage: portscan <host:dns:ip_addr:cidr>"
    exit 1
fi 

# Requires "vulscan" to scan for vulnerabilities
#
# pacaur -S vulscan-git 
# -O    Enables OS detectionA
# -sV   Enables version detection
# -sS   TCP SYN/Connect()/ACK/Window/Maimon scans
# --script=vulscan Enables vulscan script

DATE=$(date '+%Y-%m-%d')
TARGET=$@ # Pass all arguments for good measure
1=twitter

# Operating System Scan
sudo -E nmap -O $TARGET | tee out/$1-$DATE.nmap.osscan 

# Regular Port Scan
sudo -E nmap $TARGET | tee out/$1-$DATE.nmap.ports 

# HTTP 
sudo -E nmap --script=http-headers $TARGET | tee out/$1-$DATE.nmap.http 

# Common Scripts
sudo -E nmap -sC $TARGET | tee out/$1-$DATE.nmap.common 

# Vulnerability (CVE) Scan
sudo -E nmap -sV -sS --script=vulscan/vulscan.nse $TARGET | tee out/$1-$DATE.nmap.vuln

